CREATE TABLE TEMPORAL(
    -- EMPLEADO
    NOMBRE_EMPLEADO VARCHAR2(150),
    APELLIDO_EMPLEADO VARCHAR2(150),
    DIRECCION_EMPLEADO VARCHAR2(150),
    TELEFONO_EMPLEADO VARCHAR2(20),
    GENERO_EMPLEADO VARCHAR2(1),
    FECHA_NACIMIENTO_EMPLEADO DATE,
    TITULO_DEL_EMPLEADO VARCHAR2(150),
    -- PACIENTE
    NOMBRE_PACIENTE VARCHAR2(150),
    APELLIDO_PACIENTE VARCHAR2(150),
    DIRECCION_PACIENTE VARCHAR2(150),
    TELEFONO_PACIENTE VARCHAR2(20),
    GENERO_PACIENTE VARCHAR2(1),
    FECHA_NACIMIENTO_PACIENTE DATE,
    ALTURA FLOAT,
    PESO NUMBER,
    FECHA_EVALUACION DATE,
    SINTOMA_DEL_PACIENTE VARCHAR2(150),
    DIAGNOSTICO_DEL_SINTOMA VARCHAR2(150),
    RANGO_DEL_DIAGNOSTICO INTEGER,
    FECHA_TRATAMIENTO DATE,
    TRATAMIENTO_APLICADO VARCHAR2(150)
);
-- SELECT * FROM TEMPORAL;
-- SELECT COUNT(*) FROM TEMPORAL;