-- TABLE DIAGNOSTICO
INSERT INTO DIAGNOSTICO (tipoFumador)
SELECT DISTINCT DIAGNOSTICO_DEL_SINTOMA
FROM TEMPORAL
WHERE DIAGNOSTICO_DEL_SINTOMA IS NOT NULL;

-- TABLE PROFESION
INSERT INTO PROFESION (titulo)
SELECT DISTINCT TITULO_DEL_EMPLEADO
FROM TEMPORAL
WHERE TITULO_DEL_EMPLEADO IS NOT NULL;

-- TABLE SINTOMA
INSERT INTO SINTOMA (nombre)
SELECT DISTINCT SINTOMA_DEL_PACIENTE
FROM TEMPORAL
WHERE SINTOMA_DEL_PACIENTE IS NOT NULL;

-- TABLE TRATAMIENTO
INSERT INTO TRATAMIENTO (nombre)
SELECT DISTINCT TRATAMIENTO_APLICADO
FROM TEMPORAL
WHERE TRATAMIENTO_APLICADO IS NOT NULL;

-- TABLE PACIENTE
INSERT INTO PACIENTE (nombre, apellido, direccion, telefono, genero, fechaNacimiento, altura, peso)
SELECT NOMBRE_PACIENTE,
       APELLIDO_PACIENTE,
       DIRECCION_PACIENTE,
       TELEFONO_PACIENTE,
       GENERO_PACIENTE,
       FECHA_NACIMIENTO_PACIENTE,
       ALTURA,
       PESO
FROM TEMPORAL
WHERE NOMBRE_PACIENTE IS NOT NULL
GROUP BY NOMBRE_PACIENTE, APELLIDO_PACIENTE, DIRECCION_PACIENTE, TELEFONO_PACIENTE, GENERO_PACIENTE, FECHA_NACIMIENTO_PACIENTE, ALTURA, PESO;

-- TABLE EMPLEADO
INSERT INTO EMPLEADO (nombre, apellido, direccion, telefono, genero, fechaNacimiento, profesion_idProfesion)
SELECT NOMBRE_EMPLEADO,
       APELLIDO_EMPLEADO,
       DIRECCION_EMPLEADO,
       TELEFONO_EMPLEADO,
       GENERO_EMPLEADO,
       FECHA_NACIMIENTO_EMPLEADO,
       (SELECT idProfesion FROM PROFESION WHERE TEMPORAL.TITULO_DEL_EMPLEADO = PROFESION.titulo)
FROM TEMPORAL
WHERE NOMBRE_EMPLEADO IS NOT NULL
GROUP BY NOMBRE_EMPLEADO, APELLIDO_EMPLEADO, DIRECCION_EMPLEADO, TELEFONO_EMPLEADO, GENERO_EMPLEADO, FECHA_NACIMIENTO_EMPLEADO, TITULO_DEL_EMPLEADO;

-- TABLE TRATAMIENTO-PACIENTE
INSERT INTO "TRATAMIENTO-PACIENTE" (fechaTratamiento, tratamiento_idTratamiento, paciente_idPaciente)
SELECT FECHA_TRATAMIENTO,
       (SELECT idTratamiento FROM TRATAMIENTO WHERE TEMPORAL.TRATAMIENTO_APLICADO = TRATAMIENTO.nombre),
       (SELECT idPaciente FROM PACIENTE WHERE TEMPORAL.NOMBRE_PACIENTE = PACIENTE.nombre AND TEMPORAL.APELLIDO_PACIENTE = PACIENTE.apellido)
FROM TEMPORAL
WHERE FECHA_TRATAMIENTO IS NOT NULL
GROUP BY FECHA_TRATAMIENTO, TRATAMIENTO_APLICADO, NOMBRE_PACIENTE, APELLIDO_PACIENTE;

-- TABLE EVALUACION
INSERT INTO EVALUACION (fechaEvaluacion, sintoma_idSintoma, empleado_idEmpleado, paciente_idPaciente)
SELECT FECHA_EVALUACION,
       (SELECT idSintoma FROM SINTOMA WHERE TEMPORAL.SINTOMA_DEL_PACIENTE = SINTOMA.nombre),
       (SELECT idEmpleado FROM EMPLEADO WHERE TEMPORAL.NOMBRE_EMPLEADO = EMPLEADO.nombre AND TEMPORAL.APELLIDO_EMPLEADO = EMPLEADO.apellido),
       (SELECT idPaciente FROM PACIENTE WHERE TEMPORAL.NOMBRE_PACIENTE = PACIENTE.nombre AND TEMPORAL.APELLIDO_PACIENTE = PACIENTE.apellido)
FROM TEMPORAL
WHERE FECHA_EVALUACION IS NOT NULL
GROUP BY FECHA_EVALUACION, SINTOMA_DEL_PACIENTE, NOMBRE_EMPLEADO, APELLIDO_EMPLEADO, NOMBRE_PACIENTE, APELLIDO_PACIENTE;

-- TABLE DIAGNOSTICO-EVALUACION
INSERT INTO "DIAGNOSTICO-EVALUACION" (rangoDiagnostico, evaluacion_idEvaluacion, diagnostico_idDiagnostico)
SELECT RANGO_DEL_DIAGNOSTICO,
       (
        SELECT idEvaluacion
        FROM EVALUACION
        WHERE
            TEMPORAL.FECHA_EVALUACION = EVALUACION.fechaEvaluacion AND
            (SELECT idSintoma FROM SINTOMA WHERE TEMPORAL.SINTOMA_DEL_PACIENTE = nombre) = EVALUACION.sintoma_idSintoma AND
            (SELECT idEmpleado FROM EMPLEADO WHERE TEMPORAL.NOMBRE_EMPLEADO = nombre AND TEMPORAL.APELLIDO_EMPLEADO = apellido) = EVALUACION.empleado_idEmpleado AND
            (SELECT idPaciente FROM PACIENTE WHERE TEMPORAL.NOMBRE_PACIENTE = nombre AND TEMPORAL.APELLIDO_PACIENTE = apellido) = EVALUACION.paciente_idPaciente
       ),
       (
        SELECT idDiagnostico
        FROM DIAGNOSTICO
        WHERE
            TEMPORAL.DIAGNOSTICO_DEL_SINTOMA = DIAGNOSTICO.tipoFumador
       )
FROM TEMPORAL
WHERE RANGO_DEL_DIAGNOSTICO IS NOT NULL
GROUP BY RANGO_DEL_DIAGNOSTICO, SINTOMA_DEL_PACIENTE, DIAGNOSTICO_DEL_SINTOMA, NOMBRE_EMPLEADO, APELLIDO_EMPLEADO, NOMBRE_PACIENTE, APELLIDO_PACIENTE, FECHA_EVALUACION;


-- VISTAS
CREATE OR REPLACE VIEW "PACIENTES-ATENDIDOS" AS 
    SELECT empleado_idempleado idEmpleado, COUNT(DISTINCT paciente_idPaciente) pacientes_atendidos
    FROM EVALUACION
    GROUP BY empleado_idEmpleado
WITH READ ONLY;

CREATE OR REPLACE VIEW "TOTAL-PACIENTES-ATENDIDOS" AS 
    SELECT SUM(pacientes_atendidos) total_pacientes_atendidos
    FROM "PACIENTES-ATENDIDOS"
WITH READ ONLY;
