DROP VIEW "TOTAL-PACIENTES-ATENDIDOS";
DROP VIEW "PACIENTES-ATENDIDOS";

DROP TABLE "DIAGNOSTICO-EVALUACION" PURGE;
DROP TABLE DIAGNOSTICO PURGE;
DROP TABLE "TRATAMIENTO-PACIENTE" PURGE;
DROP TABLE TRATAMIENTO PURGE;
DROP TABLE EVALUACION PURGE;
DROP TABLE SINTOMA PURGE;
DROP TABLE PACIENTE PURGE;
DROP TABLE EMPLEADO PURGE;
DROP TABLE PROFESION PURGE;

DROP TABLE TEMPORAL;
